### ISSUE TITLE
Can i make drive without macOS 

### ISSUE THREAD

**Issue by jerrita** [divideconcept/MSI-GS65-GS75-P65-P75-macOS-Catalina-Hackintosh#5]
I have a GS65 9SD, but not have macOS computer, is there any other solutions? Thanks.

**Comment by erikbdev** [comment]
> I have a GS65 9SD, but not have macOS computer, is there any other solutions? Thanks.

https://dortania.github.io/OpenCore-Install-Guide/installer-guide/ You can use this guide. And if you want to install macOS and have windows in one drive then you will have to install macOS first. Honestly a bit painful, so if you have another NVMe installed on your computer I would recommend you using that.

**Comment by jerrita** [comment]
> > I have a GS65 9SD, but not have macOS computer, is there any other solutions? Thanks.
> 
> https://dortania.github.io/OpenCore-Install-Guide/installer-guide/ You can use this guide. And if you want to install macOS and have windows in one drive then you will have to install macOS first. Honestly a bit painful, so if you have another NVMe installed on your computer I would recommend you using that.

Yeah, I do have an external NVMe connected to my computer with the Lightning Triad, and want install macOS in it recently. Thanks for your help :)

**Comment by jerrita** [comment]
I used VMware to make it, and now it works. But there may also have some problems with the brightness adjustment. Although the brightness bar can be adjusted with the shortcut key, the actual display is the maximum brightness no matter how I adjust it. I've tried the QuickShade in App Store , but it didn't adjust the brightness of the cursor or some other things. So what should I do?

**Comment by divideconcept** [comment]
What exact MSI model do you have ? I have no problem adjusting the display brightness on my P65 9SE.

**Comment by divideconcept** [comment]
Oh, I just saw you have a GS65 9SD. It's a pretty similar model.

**Comment by erikbdev** [comment]
Make sure you have the latest Kexts.
